### ISSUE TITLE
Http Error 500 in the review step

### ISSUE THREAD

**Issue by gabrielizalo** [veloper/WordPress-Domain-Changer#22]
Hello,
After I select tables in this url: /wpdc/index.php/change/review appears

www.MyDomain.com is currently unable to handle this request.
HTTP ERROR 500

Any ideas why?

**Comment by veloper** [comment]
Check your syslog and apache logs for any php errors.

**Comment by veloper** [comment]
@gabrielizalo - I'm genuinely interested; What did you find?

**Comment by gabrielizalo** [comment]
Thanks for your interest but sorry.. I dont know any about PHP so I search for another solution. I installed this plugin and it works perfect: [https://wordpress.org/plugins/automatic-domain-changer/](https://wordpress.org/plugins/automatic-domain-changer/)

**Comment by veloper** [comment]
I'm glad you found a solution! Thanks for the feedback.
